### ISSUE TITLE
Adding redis cache causes my tests to hang

### ISSUE THREAD

**Issue by craigharman** [Julien-R44/bentocache#26]
I am having a very strange problem when using Redis cache and Bento.

I have Bento configured as follows:

```ts
default: 'cache',
  stores: {
    // A cache store named "cache" using
    // a in-memory cache as L1 and a Redis cache as L2
    cache: bentostore()
      .useL1Layer(memoryDriver({ maxSize: 25_000_000 }))
      .useL2Layer(
        redisDriver({
          connection: { host: env.get('REDIS_HOST'), port: env.get('REDIS_PORT') },
        })
      ),
  },
  ttl: '12h',
  gracePeriod: {
    enabled: true,
    duration: '6h',
    fallbackDuration: '5m',
  },
```

My issue is if I maintain the redis L2 cache then any tests that set the cache do not complete, they just "hang" after receiving a successful pass. Commenting out the .use2Layer related items and the tests successfully exit.

Investigating within Redis I can see 
1. Redis is running (in a docker container)
2. Bento is successfully writing the cache value. 
 
Seems like its leaving a connection open or something that causes tests not to finish.

Happy to provide more info as required.

**Comment by craigharman** [comment]
`docker-compose.yml` file looks like this:

```
services:

  st_redis:
    container_name: st_redis
    image: redis:7-alpine
    volumes:
      - redis_volume:/data
    ports:
      - 6379:6379

volumes:
  redis_volume:

```
